/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package event_management_system;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author jubel
 */
public class EventLaunch extends javax.swing.JFrame {

    /**
     * Creates new form LogInForm
     */
    Timer timer;
    int imageListCount = 0;
    private final String [] imageList = {
        "C:\\Users\\jubel\\OneDrive\\Documents\\NetBeansProjects\\event_management_system\\src\\event_management_system\\icon\\num3.jpg",
    "C:\\Users\\jubel\\OneDrive\\Documents\\NetBeansProjects\\event_management_system\\src\\event_management_system\\icon\\num4.png",
    "C:\\Users\\jubel\\OneDrive\\Documents\\NetBeansProjects\\event_management_system\\src\\event_management_system\\icon\\num5.jpg",
    "C:\\Users\\jubel\\OneDrive\\Documents\\NetBeansProjects\\event_management_system\\src\\event_management_system\\icon\\num6.png"
     };
    	
    GridBagLayout grid;
    LogFormAdmin logFormAdmin;
    LogFormUser logFromUser;
    StartingPage start;
    public EventLaunch() {
        slideShowTimerStart();
        initComponents();
        logFormAdmin = new LogFormAdmin();
        logFromUser = new LogFormUser();
        start = new StartingPage();
        grid = new GridBagLayout();
        mainLogPanel.setLayout(grid);
        GridBagConstraints gc = new GridBagConstraints();
        gc.gridx = 0;
        gc.gridy = 0;
        mainLogPanel.add(logFormAdmin,gc);
        mainLogPanel.add(logFromUser,gc);
        mainLogPanel.add(start,gc);
        start.setVisible(true);
        logFormAdmin.setVisible(false);
        logFromUser.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pixSlide = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        adminBtn = new javax.swing.JButton();
        mainLogPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pixSlide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pixSlide, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 680, 200));

        jPanel4.setBackground(new java.awt.Color(0, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/event_management_system/icon/registerNew.png"))); // NOI18N
        jButton6.setText("REGISTER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 160, 50));

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 51, 51));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/event_management_system/icon/User.png"))); // NOI18N
        jButton7.setText("USER");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 160, 50));

        adminBtn.setBackground(new java.awt.Color(255, 0, 0));
        adminBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adminBtn.setForeground(new java.awt.Color(0, 51, 51));
        adminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/event_management_system/icon/iAdmin.png"))); // NOI18N
        adminBtn.setText("ADMIN");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(adminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 160, 50));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 230));

        mainLogPanel.setBackground(new java.awt.Color(0, 51, 51));
        mainLogPanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mainLogPanelPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout mainLogPanelLayout = new javax.swing.GroupLayout(mainLogPanel);
        mainLogPanel.setLayout(mainLogPanelLayout);
        mainLogPanelLayout.setHorizontalGroup(
            mainLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        mainLogPanelLayout.setVerticalGroup(
            mainLogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(mainLogPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 370, 230));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 680, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          logFormAdmin.setVisible(true);
          logFromUser.setVisible(false);
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        logFromUser.setVisible(true);
        logFormAdmin.setVisible(false);
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void mainLogPanelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mainLogPanelPropertyChange
        // TODO add your handling code here:
       
    }//GEN-LAST:event_mainLogPanelPropertyChange

    //slide show
    
    
   /*
    // TODO add your handling code here:
         logInFormPanel.removeAll();
         logInFormPanel.repaint();
         logInFormPanel.revalidate();
        //add
        logInFormPanel.add(userPanel);
        logInFormPanel.repaint();
        logInFormPanel.revalidate();
    */ 
    private void slideShowTimerStart(){
        timer = new Timer(3000, (ActionEvent e) ->{
            setImageSize(imageListCount);
            imageListCount+=1;
            if(imageListCount>=imageList.length)
                imageListCount= 0;
        });
       
        timer.start();
      
    }
    
    public void setImageSize(int i){
        ImageIcon icon = new ImageIcon(imageList[i]);
        Image img = icon.getImage();
        Image newImage = img.getScaledInstance(pixSlide.getWidth(), pixSlide.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newImage);
        pixSlide.setIcon(newIcon); // NOI18N

    }
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventLaunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventLaunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventLaunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventLaunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventLaunch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel mainLogPanel;
    private javax.swing.JLabel pixSlide;
    // End of variables declaration//GEN-END:variables
}
